#!/usr/bin/env bash

source ${CLIGRAPHY_REPO_PATH}/setup/lib_setup.sh
oc_setup_init_app homebrew

if test $(uname) = 'Darwin'; then

    oc_info "Installing xcode command line tools if necessary"
    xcode-select --install || oc_info "Xcode command lines tools already installed"

    if ! test -x /usr/local/bin/brew; then

      oc_info "Installing homebrew"
      ruby ${CLIGRAPHY_SETUP_APP_PATH}/install.rb

    fi

    cd /usr/local

    oc_run brew update

    # FIXME - wrong python interpreter if you workon another project and run oc setup
    oc_run_ignore_fail brew upgrade
    oc_run brew install $(~/.cligraphy/python-envs/oc/bin/python ${CLIGRAPHY_REPO_PATH}/setup/packages.py ${CLIGRAPHY_SETUP_APP_PATH}/../packages.yaml)

fi

oc_success
