language: python
matrix:
  include:
  - python: '2.7'
cache:
  directories:
  - .pip_download_cache
env:
  global:
  - PIP_DOWNLOAD_CACHE=".pip_download_cache"
before_script:
- cd src/python
- pip install -r requirements.txt
- python setup.py develop
script:
- nosetests
notifications:
  email:
  - stefan@kentik.com
  - achu@netflix.com
deploy:
  provider: pypi
  user: cligraphy
  password:
    secure: l6rLUvUmsoqhX3I9ibkMvKmIohyqTBnOUA3GeiOUvWXrViS5a5uT/GEmkNXrFjzaBWkXAOtqNtoabibosU++NjaPI+Hgwlxz9y2wz2q70gDn2IuRTjIdXhWfTCUljDArU+NP/uEvFb98S/xHT/Tu5mhx6xFxlJG1JqdYtpjtMqfNiwXH+sPNOvEG9YPZrJSqnL/ke6YkdwV1TJ5IeUVEVcouJU08b+2hI7OPNp76QB+TfxRu3IaNLV+L5gVC3cI9O+t+TqdvtNZfJIlz65pgo2Ewb0fk9mPyY+73MdQKHfLaWmYQuwX9si05GLvKm8E69XslAQi+USM8zIu0fuWSeJGTvVcYF2TTtaUUlKYrl6nTei/+nFKpDwxk0EKXn9HdaUm5WXaTLvwrU51LI/dhoh/tLLuB1RLorXhTUo2xiSb3DURbwcPY0/CpCEqpzrxSKerc5Sv/t+ChXlI4bph1FdY3ab8LdzYYjN8GpNL/O4sLxTTfmbEsF3GRkqEP8bzwhcC34wqf88bPZ9eXUEP/EGzgW4iw5T5OkbP+9LE65tfagIEJGxfK7gSc4NxFCuFtk0ffdm/7ST/d81+lBtQjXAuWxawoM+wpL5jKlooo2RpEyjNzKXyDJ+K/THcDfdghBEJspoa2wDOIwnm4MOU4s2MADwoSrRhvGPrp7K702o8=
  on:
    tags: true
  distributions: sdist bdist_wheel
  skip_upload_docs: true
