language: python
matrix:
  include:
  - python: '2.7'
cache:
  directories:
  - .pip_download_cache
env:
  global:
  - PIP_DOWNLOAD_CACHE=".pip_download_cache"
before_script:
- cd src/python
- pip install -r requirements.txt
- python setup.py develop
script:
- nosetests
notifications:
  email:
  - stefan@kentik.com
  - achu@netflix.com
