#!/usr/bin/env bash

source ${CLIGRAPHY_REPO_PATH}/setup/lib_setup.sh
oc_setup_init_app pkg

if test $(uname) = 'FreeBSD'; then
    echo "Disabled"
    #    oc_run sudo pkg install -y $(~/.cligraphy/python-envs/oc/bin/python ${CLIGRAPHY_REPO_PATH}/setup/packages.py ${CLIGRAPHY_SETUP_APP_PATH}/../packages.yaml)
fi

oc_success
