#!/usr/bin/env bash

source ${CLIGRAPHY_REPO_PATH}/setup/lib_setup.sh
oc_setup_init_app yum

if test $(uname) = 'Linux'; then

    if test $(lsb_release  --id -s) = 'Fedora'; then

        # FIXME - wrong python interpreter if you workon another project and run oc setup
        oc_run sudo yum -y install $(~/.cligraphy/python-envs/oc/bin/python ${CLIGRAPHY_REPO_PATH}/setup/packages.py ${CLIGRAPHY_SETUP_APP_PATH}/../packages.yaml)

    fi

fi

oc_success
